config/routes.rb
Rails.application.routes.draw do
  resources :readings
  root to: 'readings#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reading.rb
class Reading < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_reading, only: [:show, :edit, :update, :destroy]

  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.order(created_at: :desc).limit(30)
    @reading = Reading.order(created_at: :desc).last
  end

  # GET /readings/1
  # GET /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render :show, status: :created, location: @reading }
      else
        format.html { render :new }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reading_params
      params.require(:reading).permit(:air_temperature, :water_temperature, :humidity, :total_dissolved_solids, :ph_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hydrobot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='bg-gray-800'>
    <%= yield %>
  </body>
</html>

app/views/readings/_form.html.erb
<%= form_with(model: reading) do |form| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
        <% reading.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :air_temperature %>
    <%= form.text_field :air_temperature %>
  </div>

  <div class="field">
    <%= form.label :water_temperature %>
    <%= form.text_field :water_temperature %>
  </div>

  <div class="field">
    <%= form.label :humidity %>
    <%= form.text_field :humidity %>
  </div>

  <div class="field">
    <%= form.label :total_dissolved_solids %>
    <%= form.text_field :total_dissolved_solids %>
  </div>

  <div class="field">
    <%= form.label :ph_level %>
    <%= form.text_field :ph_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='text-4xl text-center text-white font-bold mb-6'>Current Readings</h1>

<div data-controller='hello'>
  <div class='w-4/5 mx-auto'>
    <ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5">
      <li class="col-span-1 flex flex-col text-center bg-gray-800 rounded-lg shadow divide-y divide-gray-200">
        <div class="flex-1 flex flex-col">
          <figure class="highcharts-figure">
            <div id="at_speedometer" data-measurement='<%= @reading.air_temperature.round(2) %>'></div>
          </figure>
        </div>
      </li>

      <li class="col-span-1 flex flex-col text-center bg-gray-800 rounded-lg shadow divide-y divide-gray-200">
        <div class="flex-1 flex flex-col">
          <figure class="highcharts-figure">
            <div id="humidity_speedometer" data-measurement='<%= @reading.humidity %>'></div>
          </figure>
        </div>
      </li>

      <li class="col-span-1 flex flex-col text-center bg-gray-800 rounded-lg shadow divide-y divide-gray-200">
        <div class="flex-1 flex flex-col">
          <figure class="highcharts-figure">
            <div id="tds_speedometer" data-measurement='<%= @reading.total_dissolved_solids %>'></div>
          </figure>
        </div>
      </li>

      <li class="col-span-1 flex flex-col text-center bg-gray-800 rounded-lg shadow divide-y divide-gray-200">
        <div class="flex-1 flex flex-col">
          <figure class="highcharts-figure rounded-lg">
            <div id="water_temp_speedometer" data-measurement='<%= @reading.water_temperature %>'></div>
          </figure>
        </div>
      </li>

      <li class="col-span-1 flex flex-col text-center bg-gray-800 rounded-lg shadow divide-y divide-gray-200">
        <div class="flex-1 flex flex-col">
          <figure class="highcharts-figure rounded-lg">
            <div id="ph_level_speedometer" data-measurement='<%= @reading.ph_level %>'></div>
          </figure>
        </div>
      </li>

    </ul>
  </div>
</div>

<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>

app/views/readings/new.html.erb
<h1>New Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Air temperature:</strong>
  <%= @reading.air_temperature %>
</p>

<p>
  <strong>Water temperature:</strong>
  <%= @reading.water_temperature %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @reading.humidity %>
</p>

<p>
  <strong>Total dissolved solids:</strong>
  <%= @reading.total_dissolved_solids %>
</p>

<p>
  <strong>Ph level:</strong>
  <%= @reading.ph_level %>
</p>

<%= link_to 'Edit', edit_reading_path(@reading) %> |
<%= link_to 'Back', readings_path %>